### ISSUE TITLE
User Bookshelf Page

### ISSUE THREAD

**Issue by CheesyGamer77** [COSC481W-2023Fall/Bookworm#19]
As a user, I want to be able to manage my own personal list of books I'm reading, planning to read, and completed under one page.

- **Persona:** Users who wish to track which books they've read, are reading, or plan to read.
- **Feature:** A way for users to add books to their bookshelf
- **Business Value:** Users can see other user's books that they've read, plan to read, and completed

**Tasks:**
- [ ] Implement a bookshelf page template
- [ ] Add appropriate API routes for bookshelf CRUD operations
- [ ] Add a new bookshelf property on the user in the database
- [ ] Add a button on the book template for users to add a book to one of their bookshelves

**Acceptance Criteria:**
1. Pass applicable unit tests
2. Users can visit a particular book's page and add it to one of their bookshelves
3. Users can specify which bookshelf the book should be added to
