### ISSUE TITLE
bug: Sign-up page is rendered briefly on refresh or page change

### ISSUE THREAD

**Issue by nacxitl** [COSC481W-2023Fall/Bookworm#25]
The sign-up page is briefly rendered every time any page is rendered.

**Tasks**

- [ ] Investigate the cause of the bug.
- [ ] Fix the bug.

**Acceptance Criteria**
- [ ] Sign-up page is no longer rendered briefly on each refresh
