### ISSUE TITLE
bug: Refreshing breaks the app

### ISSUE THREAD

**Issue by nacxitl** [COSC481W-2023Fall/Bookworm#27]
When you refresh any page other than the home page at route '/' the website stops serving our app and shows an nginx error. This is the same issue we encountered in the demo project. This issue is only on the deployed app.

**Tasks**
- [x] Investigate cause of the bug.
- [x] Fix the bug.

**Acceptance Criteria**

- [x] Bug is investigated and fixed.

**Comment by nacxitl** [comment]
Thank you stackoverflow! https://stackoverflow.com/questions/43555282/react-js-application-showing-404-not-found-in-nginx-server

Closes #27
