### ISSUE TITLE
bug: Browse page doesn't work on deployed app

### ISSUE THREAD

**Issue by nacxitl** [COSC481W-2023Fall/Bookworm#28]
The browse page doesn't work on the deployed app. The API calls fail to return any kind of response.

**Tasks**
- [ ] Investigate the bug.
- [ ] Fix the bug.

**Acceptance Criteria**
- [ ] Cause of the bug has been investigated.
- [ ] Bug is fixed.

**Comment by CheesyGamer77** [comment]
This is confirmed. This is caused by CORS errors due to mismatched origin. We currently hardcode our CORS origin in our backend index file as something that will match on dev builds, but not on production.

I'm currently working on a fix for this which will be deployed before midnight.

**Comment by CheesyGamer77** [comment]
This has been patched on production, but will be keeping this open until a permanent solution is merged

**Comment by CheesyGamer77** [comment]
Fixed in #30
