### ISSUE TITLE
User Profile Page

### ISSUE THREAD

**Issue by CheesyGamer77** [COSC481W-2023Fall/Bookworm#32]
As a user I'd like to have a profile page. The page should show my username and profile picture. My profile picture should be the first letter in my username.

- **Persona:** Users who wish to see other users on the application
- **Feature:** User profile page
- **Business Value:** Users can see each-other's profiles

**Tasks:**

- [x] Add "Profile" button functionality
- [x] Set the profile button to be visible on the navbar when the user is logged in
- [x] Redirect the user to a template profile page when clicked
- [x] Setup appropriate CSS styles

**Acceptance Criteria:**

1. Profile button only shows when the user is logged in
2. Profile button directs to the user's profile page
3. Profile picture is automatically generated based off the first letter of their username
