### ISSUE TITLE
Book View Page

### ISSUE THREAD

**Issue by CheesyGamer77** [COSC481W-2023Fall/Bookworm#36]
As a book user , I want to navigate to a unique page for each book that shows information about a particular book, such as author, publisher, genres, and title

**Tasks:**
- [x] Setup UI template for book page

**Acceptance Criteria:**
- [x] Users can navigate to a page that displays information about each individual book
- [x] Users can view all the information associated with that particular book
