### ISSUE TITLE
User Account Sign-In/Sign-Out

### ISSUE THREAD

**Issue by CheesyGamer77** [COSC481W-2023Fall/Bookworm#4]
As a user, I'd like to be able to sign in and sign out of my account that I have registered for

**Tasks**

- [ ]  Setup UI for signing in
- [ ] Setup UI for signing out
- [ ] Implement account sessions

**Acceptance Criteria**:
- Users can sign in to their account
- Users are prevented from signing in to their account if they provide incorrect details
- Users that are signed in can sign out of their account successfully

**Comment by CheesyGamer77** [comment]
Blocked by #3
