### ISSUE TITLE
Browse Sorting

### ISSUE THREAD

**Issue by CheesyGamer77** [COSC481W-2023Fall/Bookworm#49]
As a user, I want to be able to sort my browse results by a number of criterion such as publication date, most reviewed vs least reviewed, and average rating

**Tasks:**
- [x] Modify search results template to allow users to sort book views

**Acceptance Criteria:**
- [x] Pass applicable unit tests
- [x] Users can sort their browse/search results by publication date, review count, and average rating
- [x] Users can apply one or more of the above criterion for more-granularity
