### ISSUE TITLE
Review Profile Icons

### ISSUE THREAD

**Issue by CheesyGamer77** [COSC481W-2023Fall/Bookworm#52]
# PBI: Review Profile Icons

## User Story
As a user, I'd like for the icon shown on any reviews I submit to be of my profile icon, not the book icon.

- **Persona:** A user who wishes to review books
- **Feature:** Use review author icon as review image, instead of the book's icon
- **Business Value:** Users can more easily identify other users' reviews based on their review icon

## Reference to the Beta Testing
**Beta Testing Report:** https://docs.google.com/document/d/1V6lao3VZSPdxv9f12x7VdEaQtUq4LibccvuiHjvWT84/edit?usp=sharing

**Item 8g:**
> They submitted a review for the book, and found it weird that the image used for the review author picture is the same as the image used for the book, and not the user’s avatar

## Tasks
- [x] Refactor `ShowUserAvatar` component to allow username to be explicitly passed instead of only via route params
- [x] Refactor `ShowUserAvatar` component to allow customizable sizing of the icon itself and the inner text
- [x] Refactor `ReviewBox` to use `ShowUserAvatar` instead of openlibrary image for book

## Acceptance Criteria
1. The username for `ShowUserAvatar` can be customized using a `name` prop
2. The icon size for `ShowUserAvatar` can be customized using a `size` prop
3. The text inside `ShowUserAvatar` scales automatically with the size of the icon itself
4. Icons for each review match the review author's avatar
