### ISSUE TITLE
Sign-up Page Consistency

### ISSUE THREAD

**Issue by CheesyGamer77** [COSC481W-2023Fall/Bookworm#53]
# PBI: Sign-up Page Consistency

## User Story
As a user, I'd like for the sign-up page to be more consistent with the sign-in page. The site name should be "BookWorm", not "Bookwormer", and the password field should allow me to view it's contents if I wish.

- **Persona:** A user who wishes for better UI/UX consistency across our application
- **Feature:** Fix a typo ("Bookwormer"), and add "view password eye" similar to the password field in the sign-in page so that they can view their password as they sign up
- **Business Value:** Users signing up for the site have a similar UI/UX experience as when signing-in

## Reference to the Beta Testing
**Beta Testing Report:** https://docs.google.com/document/d/1V6lao3VZSPdxv9f12x7VdEaQtUq4LibccvuiHjvWT84/edit?usp=sharing

**Item 5a:**
> The tester immediately noticed that the form is titled “Bookwormer Registration” instead of “BookWorm registration”.

**Item 6a:**
> The tester noticed that, while they could view their password by clicking the “eye” icon on the sign-in page, they couldn’t do so on the sign-up page.

## Tasks
- [x] Refactor Sign-Up page to use Ant Design's HTML form abstraction instead of default HTML form
- [x] Refactor CSS styles to apply to the newly refactored Sign-Up form
- [x] Change sign-up form title from "Bookwormer Registration" to "BookWorm Registration"
- [x] Add "eye icon" on password field on sign-up form to match behavior in sign-in page.
- [x] Refactor profile edit page to use Ant Design's HTML form abstraction instead of default HTML form

## Acceptance Criteria
1. The typo on the sign-up page is fixed
2. Users can click on an "eye" icon on the password field in sign-up to see what they've typed, just like on the sign-in page
3. The form input boxes for the sign in page, sign up page, and profile edit page are all similar in style
