### ISSUE TITLE
404 Error Page

### ISSUE THREAD

**Issue by Leslie48197** [COSC481W-2023Fall/Bookworm#64]
**User Story**
As a user, when I access a page which doesn't exist, it should show me some 404 error messages.

**Persona:** A user who accesses an invalid page
**Feature:** Show some 404 page not found messages 
**Business Value:** Users can get clearer and more concise information

**Reference to the Beta Testing Report:**
https://docs.google.com/document/d/1TZuE4fjLCdFrmtiAOvF-rzfzzZ7HIpEZ/edit?usp=drive_link&ouid=102220693003020992658&rtpof=true&sd=true
**item 6a:**
The page should show users some 404 page not found messages.

**Tasks:**

- [x]  Add error page route to App.tsx file.
- [x] Create error page and its css file.

**Acceptance Criteria:**

- [x]  Users can access those invalid page, but it will show some 404 messages to remind them.
